import { sha256 } from '@noble/hashes/sha256';
import { bytesToHex, hexToBytes, concatBytes } from '@noble/hashes/utils';
import * as secp from '@noble/secp256k1';

/** 32-byte hex nonce generated by the browser. */
export function generateNonce(): string {
  const buf = new Uint8Array(32);
  crypto.getRandomValues(buf);
  return bytesToHex(buf);
}

/**
 * Derive a secp256k1 keypair from an ECDSA signature and a nonce.
 *
 *   privkey = SHA256(signature || nonce)
 *
 * The server sees the signature (LNURL-auth). The browser holds the nonce.
 * Neither alone can derive the key.
 */
export function deriveKey(signatureHex: string, nonceHex: string): SplitSigKey {
  const privBytes = sha256(concatBytes(hexToBytes(signatureHex), hexToBytes(nonceHex)));
  const pubBytes = secp.getPublicKey(privBytes, true); // compressed 33-byte

  return {
    privateKey: bytesToHex(privBytes),
    publicKey: bytesToHex(pubBytes),
    publicKeyXOnly: bytesToHex(pubBytes.slice(1)), // 32-byte x-only (Schnorr / taproot)
  };
}

/**
 * Derive the public key only (no private key returned).
 * Use this server-side to verify a registered pubkey without handling secrets.
 */
export function derivePublicKey(signatureHex: string, nonceHex: string): string {
  return deriveKey(signatureHex, nonceHex).publicKeyXOnly;
}

/**
 * Verify that a public key was derived from a given signature + nonce.
 */
export function verify(signatureHex: string, nonceHex: string, expectedPubKeyXOnly: string): boolean {
  return deriveKey(signatureHex, nonceHex).publicKeyXOnly === expectedPubKeyXOnly;
}

export interface SplitSigKey {
  /** 32-byte hex private key */
  privateKey: string;
  /** 33-byte compressed public key (hex) */
  publicKey: string;
  /** 32-byte x-only public key (hex) — for Schnorr/taproot/Nostr */
  publicKeyXOnly: string;
}

// Re-export utils for convenience
export { bytesToHex, hexToBytes } from '@noble/hashes/utils';
